// <auto-generated />
namespace UpFinancas.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class model_evento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model_evento));
        
        string IMigrationMetadata.Id
        {
            get { return "201603012356549_model_evento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
