// <auto-generated />
namespace UpFinancas.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_models_formas_e_categorias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_models_formas_e_categorias));
        
        string IMigrationMetadata.Id
        {
            get { return "201604302023248_add_models_formas_e_categorias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
